### ISSUE TITLE
Parse comma decimal numbers to dot decimal numbers

### ISSUE THREAD

**Issue by masterwendu** [nobt-io/frontend#62]
It is not possible to add a bill with a comma separated amount like (2,30 €). Tested with Firefox Mobile. You should also allow such inputs and parse it on saving. Moreover is the error message not very useful.
![screenshot_20170911-102148](https://user-images.githubusercontent.com/12148533/30265065-3f7f72be-96db-11e7-90b6-989f9b685070.png)

**Comment by thomaseizinger** [comment]
Hi @masterwendu!
I agree that the error message is not very helpful. A decimal amount should work though. I will look into it!

**Comment by thomaseizinger** [comment]
The problem is that Firefox triggers the onChange handler only on `blur` whereas chrome triggers it on every keystroke. This only happens for input fields of type `number`.
Therefore our input-validator, which is bound to the onChange event, is not triggered in Firefox. Unfortunately, there is no consistent support across mobile browsers for other events like onKeyPress, onKeyDown or onKeyUp. I haven't found a solution yet, that works across all browsers and delivers a good user experience.

**Comment by masterwendu** [comment]
Oh ok,
Then I would trigger `input-validator` `onBlur` and on save of the bill.
Or is this a issue?

**Comment by thomaseizinger** [comment]
The whole idea of the validator was to provide assistance to the user as they type so that they can never enter an invalid amount. So triggering the validator `onBlur` doesn't really help.
